### PR TITLE
A big ugly hack to make one of trinity's test pass again

### PR DESCRIPTION
**Pull request by gsalgado**
Something like this will be needed to keep that trinity test passing if we want to get rid of the code in `AsyncioIsolatedComponent` that duplicates something we already have in `open_in_process()`

### CODE REVIEW

**Comment by pipermerriam** [comment]
As convoluted and nasty as this is, I could be ok with it.  Any chance there's a test we could write that covers this new behavior?

**Comment by gsalgado** [comment]
> Any chance there's a test we could write that covers this new behavior?

I spent almost a day trying to reproduce it in a simpler test, without any luck

**Comment by gsalgado** [comment]
I've refactored things a bit to make it slightly less ugly.

**Comment by gsalgado** [comment]
No longer needed

**Pull request closed without merging**
